"""add rooms and room members

Revision ID: 7b67afc0ac7b
Revises: 4d64161b6cd8
Create Date: 2026-08-27 14:45:34.111808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b67afc0ac7b'
down_revision: Union[str, Sequence[str], None] = '4d64161b6cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('event', sa.String(length=32), nullable=False))
    op.drop_column('rooms', 'competition')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('competition', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'event')
    # ### end Alembic commands ###
