"""increase solve penalty length

Revision ID: d8cbd2be52fe
Revises: a64323e8b3a2
Create Date: 2026-08-31 08:45:35.572587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8cbd2be52fe'
down_revision: Union[str, Sequence[str], None] = 'a64323e8b3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solves', 'penalty',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solves', 'penalty',
               existing_type=sa.String(length=4),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    # ### end Alembic commands ###
